### PR TITLE
Small bugfixes and new feature

### PR DESCRIPTION
**Pull request by apuigsech**
I fixed two small problems; One typo on the README file, and a problem when using Default field values where the default value were never used.

I also added support to add Parameters on Field Hooks that can be useful in some cases.

### CODE REVIEW

**Comment by rs** [comment]
Could you please split those different changes into their own PRs?

**Comment by apuigsech** [comment]
That's what I tried oIt's what I tried at first instance, but failed :(

This afternoon I'll fix it.

**Comment by apuigsech** [comment]
Splited into 3 PRs.

**Comment by rs** [comment]
Thx

**Pull request closed without merging**
