### PR TITLE
response: Fix _etag formatting in list items

### PR DESCRIPTION
**Pull request by Dragomir-Ivanov**

### CODE REVIEW

**Comment by rs** [comment]
Why do we need to do that in payload? The weak etag format is only relevant when used as an HTTP header.

**Comment by smyrman** [comment]
> Why do we need to do that in payload? The weak etag format is only relevant when used as an HTTP header.

Valid point; there is no need to worry about the _etag in the payload being weak or not. I suppose we can close this review then.

**Comment by smyrman** [comment]
@Dragomir-Ivanov, any thoughts?

**Comment by Dragomir-Ivanov** [comment]
Yes, makes sense. Since this is actual resource ETag, then it must be strong.

**Pull request closed without merging**
