### PR TITLE
WIP: Add missing query import to README example

### PR DESCRIPTION
**Pull request by mishak87**

### CODE REVIEW

**Comment by smyrman** [comment]
Clicked the "Update branch" button in GitHub, but it might be better if you do a rebase and I can merge it.

PS! It's perhaps better for the future, if you have many minor changes to the README, that we do them as one PR.

**Comment by smyrman** [comment]
Also, if you have a work in progress PR that you don't want me to merge right away, you can do a DRAFT PR.

- https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by mishak87** [comment]
Sorry for spamming I can keep this one open till end of the week if I find more typos in documentation.

**Comment by smyrman** [comment]
NP. We should probably create a contribution guide at some point 👍

**Comment by smyrman** [comment]
@mishak87, if you want to squash your commits, I can rebase and merge.

**Comment by mishak87** [comment]
Rebased and squashed typos. I found the last one by accident.
_Finally after two months I am getting back to programming 😆_

**Comment by smyrman** [comment]
Rebased & merged :-)

**Pull request merged**
