### PR TITLE
Recalculate ETag after OnUpdate/OnInsert hooks, before storing. Fixes…

### PR DESCRIPTION
**Pull request by Dragomir-Ivanov**
… #255

### CODE REVIEW

**Comment by Dragomir-Ivanov** [comment]
About documentation...since this behavior sound common sense, do I still need to add some clarification in the README?

**Comment by smyrman** [comment]
Probably it's OK without additional documentation at this stage.

**Comment by smyrman** [comment]
@Dragomir-Ivanov, do you consider this ready for merge?

**Comment by smyrman** [comment]
If you can, maybe improve the commit message according to these conventions:
- https://chris.beams.io/posts/git-commit/

Especially the subject line. E.g.

```
Recalculate E-Tag right before before storing items

E-tags used to be set after parsing an item only, before potential hooks
alter the item content. This change adds a final step to resource Update
and Create operations to recalculate E-tags right before passing items
to the Storer back-end.

Fixes #257 
```

Or something like that

**Comment by Dragomir-Ivanov** [comment]
Thanks for the suggestion @smyrman. Recommitted with the new message & ready for merge.

**Pull request merged**
