### PR TITLE
json: Unmarshall JSON numbers as json.Number type

### PR DESCRIPTION
**Pull request by Dragomir-Ivanov**
This could theoretically allow us to support other number types, such as `Decimal` and being able to transport it via JSON:
```
{
    "value" : 1.23
}
```

instead quoted number
```
{
    "value" : "1.23"
}
```

@smyrman  Still not sure about this.

### CODE REVIEW

**Comment by Dragomir-Ivanov** [comment]
Seems like I missed `query/` tests.

**Comment by smyrman** [comment]
No the intend was to start a discussion on it first.

**Comment by smyrman** [comment]
But I suppose the PR makes the discussion easy to have.

**Comment by smyrman** [comment]
I think it gives nice leeway, but I want to hear @rs opinion. Is it worth switching to `json.Number` to allow more leeway in e.g. fixed decimal implementations for applications and/or Storere backends? The implementations could of-course still _choose_ to rely on strings.

**Comment by rs** [comment]
Wouldn't it be better to keep current integer/float validation untouched and deal with decimals using a specific validator that would enforce the value to be un/serialized as a string to keep the right representation?

**Comment by Dragomir-Ivanov** [comment]
@rs Agreed, it is sane to keep "custom" types always encoded as strings. Will make a PR to rs-layer-mongo soon.

**Comment by smyrman** [comment]
First of all, I think this does not need to be done _now_. You can perfectly well implement a Decimal type that supports only string encoding, and that would probably be the most useful, and the best place to start, as you have already pointed out @Dragomir-Ivanov.

My intent with reopening #125  rest-layer side, was just so we could discuss if it was also worthwile to consider adding leeway in rest-layer to do more than that (in good time). Thanks for this code demonstration though.

> deal with decimals using a specific validator that would enforce the value to be un/serialized as a string to keep the right representation?

@rs , how could you do that when the payload is  always decoded into a `map[string]interfave{}`? The only way to do parse a numeric JSON tag into a number specifically for one field would be to use structs as schemas, or massivly complicate the decoding process.

Therefore _if_ we want a fixed Decimal type that supports JSON numeric encoding as well as string encoding, and maybe we don't btw, then this is probably the best aproach as it leaves all numbers in their most pure original string form until they reach the validator.

**Comment by rs** [comment]
If decimals are stored as strings there is nothing special JSONwize to have them parsed. It is the role of the validator to have them checked and eventually transformed if necessary.

**Comment by smyrman** [comment]
@rs, yes. That has always been clear.

**Comment by smyrman** [comment]
Or depends what you mean as "stored as string" @rs. `json.Number` is a string in go, just as the whole JSON payload is a string, or byte slice in go.

The point is that if we want to parse  number literals in JSON (a string or byte slice withot surrounding double quotes), today that number is parsed directly into a float64 or int64 before it even reach the validator, is it not?

If we want to add leeway to add numeric FieldValidators with a higher or different precision than float64, we need to use `json.Number` when parcing into `map[string]interface{}` to avoid loosing precision.

Fixed decimal is only an example. Another example would be big ints/ floats.

**Comment by smyrman** [comment]
And btw, maybe the answer is we don't need such leeway. Maybe such numeric types would be restricted to use string literals in JSON when combined with rest-layer, meaning a byte slice where the first and last char is a double quote.

**Comment by rs** [comment]
I would keep it simple. I see no practical use-case where the current behavior would be an issue. Do you have some?

**Comment by smyrman** [comment]
Not an issue as such, as this is just a discussion on style.

Support for big int/float could matter for scientific applications, and fixed decimal could be essential for financial application, but there is no case that _demands_ these types to be encoded as a numeric literal in JSON.

Let's close it for now anyway :+1:

**Pull request closed without merging**
