### PR TITLE
Fix fields projections on nested sub-resources. Adds validation on fi…

### PR DESCRIPTION
**Pull request by Dragomir-Ivanov**
…eld projection for `Connected` resources.

This PR helps with following scenario:
- Having this resource graph
```
	index := resource.NewIndex()
	aa := index.Bind("a", a, mem.NewHandler(), resource.Conf{AllowedModes: resource.ReadWrite})
	bb := aa.Bind("b", "id", b, mem.NewHandler(), resource.Conf{AllowedModes: resource.ReadWrite})
	bb.Bind("c", "id", c, mem.NewHandler(), resource.Conf{AllowedModes: resource.ReadWrite})
```
Being able to correctly execute queries like `/a?fields=b{c}`

### CODE REVIEW

**Comment by Dragomir-Ivanov** [comment]
Thanks guys. I think I have added everything I needed to `rest-layer`, so this may be my last patch for now. I will keep eye on the any issues on GitHub, and will support and try to help as much as I can.
Special thanks for @smyrman for his guidance and patience.

**Comment by Dragomir-Ivanov** [comment]
Guuy, hold off with the merge. I thing there is some problem.

**Comment by Dragomir-Ivanov** [comment]
Okay, I think I fixed the issue with the latest patch.

**Comment by smyrman** [comment]
@Dragomir-Ivanov, when you are ready, please squash your commits to one and we can do a merge.

I would recommend the final commit message to follow the [50/72 rule](https://chris.beams.io/posts/git-commit/), but won't review it in particular.  This does however make the commit more readable in many tools, both CLI, web and GUI.

**Comment by Dragomir-Ivanov** [comment]
Done. Thanks for the link.

**Pull request merged**
