### PR TITLE
Resolves rs/rest-layer#153 linted README Markdown.

### PR DESCRIPTION
**Pull request by SAFAD**

### CODE REVIEW

**Comment by rs** [comment]
Go code uses tab for indentation. Why do you want to use space instead?

**Comment by smyrman** [comment]
Actually, the README is using a mix if tabs and spaces atm, also for (Go) code examples, probably due to being copy-pasted in from various sources.

I don't mind which is used for Markdown, spaces or tabs, but it's nice to make it consistent. Sicking with some linter's default option may be the road of shortest resistance. @SAFAD, which linter did you use?

**Comment by smyrman** [comment]
> Actually, the README is using a mix if tabs and spaces atm, also for (Go) code examples

Actually, Go code seams to be mostly using tabs, while terminal example code is using spaces in master atm.

**Comment by SAFAD** [comment]
@rs @smyrman Yes I know that Go indentation is tab based, however [markdownlint](https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md) kept whining about it.

We can use the following to make the linter ignore the Hard tabs in Go code:

> ```<!-- markdownlint-disable MD010 -->```
> ```go
> users := index.Bind("users", user, mem.NewHandler(), resource.Conf{
> 	AllowedModes: []resource.Mode{resource.Read, resource.List, resource.Create, resource.Delete},
> })
> ```
> ```<!-- markdownlint-enable MD010 -->```

Shall I push a new commit to match this style for each Go code block ?

**Comment by smyrman** [comment]
I would vote for using the linter default, and go with all spaces as is suggest in this PR, if @rs is OK with it. It's a small replacement job if you copy-paste from Go, but if we get a linter to do the job, it's probably not to much of a hassle.

Linter exception code (be it Markdown Go or otherwise) is a bit unfortunate in my opinion as it hurts readability and maintainability, and ties development to using a given linter software.

That said, I will leave the final word to @rs to decide.

**Comment by rs** [comment]
The linter should not complain about what is in a code blocks. I think it’s a linter problem here.

**Comment by smyrman** [comment]
@SAFAD, would you like to update this PR when you have time to not re-indent the Go code-blocs, and also not add any linter exception comments?

**Comment by smyrman** [comment]
Otherwise I think we will just close it.

**Comment by SAFAD** [comment]
I will be updating this PR during this week, please hold on closing it for now :)

**Comment by smyrman** [comment]
Closing (fixed in new PR)

**Pull request closed without merging**
