### PR TITLE
jsonschema: #51 - split into multiple files

### PR DESCRIPTION
**Pull request by smyrman**
This change splits the encoder logic into a separate file per supported
schema.FieldValidator type. It also provides some minor clenaups to the
documentation and adds some FIXME statements.

Functions / type defintions are declared in the order in which they are
called, which should make the code "read like an article from top to
bottom".

This cleanup provides the second step of #51.

### CODE REVIEW

**Comment by smyrman** [comment]
CC @yanfali and @rs

**Comment by smyrman** [comment]
I think the failures here are related to #69 not being merged.

**Comment by smyrman** [comment]
Chnges has been rebased.

**Comment by rs** [comment]
Is it ready to merge?

**Comment by smyrman** [comment]
Yes

**Pull request merged**
